apiVersion: v1
data:
  # change base64 to actual values
  DB_HOST: base64encoded
  DB_NAME: base64encoded
  DB_PASSWORD: base64encoded
  DB_PORT: base64encoded
  DB_USER: base64encoded
kind: Secret
metadata:
  creationTimestamp: "2024-06-13T23:23:20Z"
  name: db-secret
  resourceVersion: "18056"
  uid: fa33d98d-bd42-4888-b280-fd7588d83040
type: Opaque
