apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
spec:
  backoffLimit: 3
  template: 
    spec:
      restartPolicy: OnFailure 
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      initContainers:
        - name: wait-for-postgresql
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              until nc -z cve-postgresql.dev.svc.cluster.local 5432; do
                echo "Waiting for PostgreSQL to be ready..."
                sleep 5
              done
        {{- range .Values.initContainers }}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
            {{- end }}
        {{- end }}
      containers:
        {{- range .Values.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
            {{- end }}
        {{- end }}

    
