apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}"
spec:
  imagePullSecrets:
    {{- range .Values.imagePullSecrets }}
    - name: {{ .name }}
    {{- end }}
  initContainers:
    {{- range .Values.initContainers }}
    - name: {{ .name }}
      image: {{ .image }}
      imagePullPolicy: {{ .imagePullPolicy }}
      env:
        {{- range .env }}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              name: {{ .valueFrom.secretKeyRef.name }}
              key: {{ .valueFrom.secretKeyRef.key }}
        {{- end }}
    {{- end }}
  containers:
    {{- range .Values.containers }}
    - name: {{ .name }}
      image: {{ .image }}
      imagePullPolicy: {{ .imagePullPolicy }}
      env:
        {{- range .env }}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              name: {{ .valueFrom.secretKeyRef.name }}
              key: {{ .valueFrom.secretKeyRef.key }}
        {{- end }}
    {{- end }}
