apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
spec:
  backoffLimit: 3
  template: 
    spec:
      restartPolicy: OnFailure 
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      containers:
        {{- range .Values.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
            {{- end }}
            - name: {{ .processor.name }}
              value: {{ .processor.url }}
        {{- end }}
